# Generated by Django 4.2.7 on 2024-05-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_fooditem_passengerdetails_delete_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('food_item', models.CharField(max_length=100)),
                ('amount_of_food', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PassengerDetails',
        ),
    ]
