# Generated by Django 4.2.7 on 2024-05-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_fooddonation_amount_of_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=10)),
                ('student_id', models.CharField(max_length=15)),
                ('home_town', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Robotics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=10)),
                ('student_id', models.CharField(max_length=15)),
                ('home_town', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=10)),
                ('student_id', models.CharField(max_length=15)),
                ('home_town', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Steam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=10)),
                ('student_id', models.CharField(max_length=15)),
                ('home_town', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FoodDonation',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
